version: '3.8'
services:
  # school Project: Spring Boot
  school-app:
    build:
      context: ./school
      dockerfile: Dockerfile
    ports:
      - "9001:9000"  # Uygulamanın 9000 portunu 9001 üzerinden yayınlıyoruz.

  # schoolRegister Project: Spring Boot ve MySQL
  school-register-app:
    build:
      context: ./schoolRegister
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://school-register-mysql:3306/test-db
      SPRING_DATASOURCE_USERNAME: omer  # MySQL kullanıcısı
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8080"  # Uygulamanın 8080 portunu 8081 üzerinden yayınlıyoruz.
    depends_on:
      - school-register-mysql
    restart: always
  # MySQL service for schoolRegister
  school-register-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test-db
      MYSQL_USER: omer
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
